### ISSUE TITLE
Roadmap 1.0.0

### ISSUE THREAD

**Issue by ije** [alephjs/aleph.js#461]
Before we release the **1.0.0**, a few more things need to be done:

- [ ] bundle modules when execute `build` command, but keep **ESM** format
- [ ] routes `generate` mode that allows you to run the `server.tsx` without the CLI
- [ ] cache API for SSR/build output
- [ ] better error handling
- [ ] [framework](https://github.com/alephjs/aleph.js/tree/main/framework/vue) support for Vue.js (**if anyone has interesting in implementing this, please PM i@jex.me**)
- [ ] add more showcases (HN clone, GitHub OAuth middleware, Styled-Components SSR, ...), all the apps need to be deployed to [Deno Deploy](https://deno.com/deploy)
- [ ] docs update: https://github.com/alephjs/alephjs.org/pull/58
