### ISSUE TITLE
v0.3.0

### ISSUE THREAD

**Issue by ije** [alephjs/aleph.js#5]
Here's the roadmap for **v0.3.0** updates.

## Features

- [x] ~~**Scripts** component to add custom scripts(like *ga.js*, etc)~~
- [x] ~~**useEnv** hook~~
- [x] postcss processor
- [x] postcss config (`postcss.config.json` or *postcss* in `aleph.config.js`)
- [x] plugin system
- [x] ~~new jsx transform~~
- [x] inline style

### New jsx transform

~~with new jsx transform, now we can use jsx without importing `React` and aleph's components:~~

We have decided to postpone this feature until later. See #94 for details.

```typescript
export default function App() {
  return (
    <>
      {/* custom head */}
      <head>
        <title>Hello World</title>
      </head>

      {/* inline CSS */}
      <style>{`
        :root {
          --theme-color: #d63369;
        }
      `}</style>

      {/* import css */}
      <link rel="style" href="../styles/app.css" />

      {/* import componeny asynchronously */}
      <link rel="component" href="../components/logo.tsx" data-props={{ size: 200 }} data-fallback={<div>Loading...</div>} />

      {/* redirct pages */}
      <a href="/about">About</a>

      {/* nav link */}
      <a rel="nav" data-active-className="active" data-active-style={{color: 'red'}} href="/about">About</a>

      {/* prefetch pages */}
      <a rel="prefetch" href="/about">About</a>

      {/* custom scripts */}
      <script src="/ga.js"></script>
      <script>{`
       function gtag() {
        dataLayer.push(arguments)
        }
        window.dataLayer = window.dataLayer || [];
        gtag("js", new Date());
        gtag("config", "G-1234567890");
      `}</script>
    </>
  )
}
```

### Inline CSS

add inline css in `style` tag with **SSR** support:

```typescript
export default function App() {
  return (
    <>
      <h1>Hello World</h1>
      <style>{`
        h1 {
          color: #d63369;
        }
      `}</style>
    </>
  )
}
```

## New Compiler&Bundler (#28)

- [x] use [swc](https://github.com/swc-project/swc) compiler in Rust instead of tsc
- [x] bundle deps with polyfills in production mode

![Screen-Shot-2020-11-24-at-23 02 22](https://user-images.githubusercontent.com/2883484/100112689-7cea9b00-2eaa-11eb-9f54-09323bd71563.png)

## Plugins
- [x] sass (improved by @shadowtime2000 (#41))
- [x] wasm

## APIs
- [x] `decodeBody` (#35) thanks @shinspiegel

## Server

- [x] gzip/br encoding
- [ ] path rewrites
- [ ] support custom server(oak?)
- [ ] https(tls)

## Improvements

- [ ] `init` command UI (#47)
- [ ] ErrorBoundary UI
- [ ] **cli** output

## Optimization

- [x] modulepreload (#9) @shadowtime2000 
- [ ] SSR cache to local drive
- [x] cache remote deps automaticlly

### Code
- [x] ~~use `deno fmt`~~
- [ ] full jsDoc
- [ ] full testing

### Examples

- [x] spa-app
- [x] hi
- [ ] markdown docs
- [ ] markdown blog
- [ ] restful blog
- [ ] graphql blog
- [x] with plugins
- [x] default-src-directory

## Deployment platform support

- [ ] [Vercel](https://vercel.com)
  - [x] build
  - [ ] APIs(functions)
- [ ] [Netlify](https://netlify.com)
  - [ ] build
  - [ ] APIs(functions)

**Comment by lucacasonato** [comment]
> use https://alephjs.org/mod.ts import URL

Are the urls not going to be versioned?

**Comment by ije** [comment]
@lucacasonato `https://alephjs.org/mod.ts` may map to the cli version during the compilation, it's a vague idea

**Comment by lucacasonato** [comment]
Interesting. I would be careful about magic resolving like that though. It will break all kinds of tooling (deno info, deno cache, deno vscode extension).

**Comment by shadowtime2000** [comment]
As of v1.5.0 `Deno.bundle` supports tree shaking so you could also look into that as an alternative to `system.js`.

**Comment by mohsenkhanpour** [comment]
Aleph.js looks very promising. I have some suggestions:
1. Designing a plugin API so the community can also contribute to ecosystem.
2. Using a monorepo, so the code related to core and plugins, and examples are separated.
3. Use a folder named `static` for holding static files and build output to `public` rather than `output`. This is usually the convention and hosting services have defaults for this folder.
4. Regarding: support custom server(oak?) -> You can see [Sapper](https://sapper.svelte.dev/docs#src_server_js) for implementation references.
5. Create a Discord server for communication.

**Comment by ije** [comment]
thanks for your kind suggestions!
1. Aleph.js already has a plugin system, pleas check [plugins](https://github.com/alephjs/aleph.js/tree/master/plugins) and [example](https://github.com/alephjs/aleph.js/tree/master/examples/with-plugins).
2. Aleph.js works in Deno, `monorepo` is just Url prefix, will do in the future on-demand.
3. this repository is a library, directory `public` and `dist`(SSG output) will be applied  in your application.
4. i like **Sapper** too.
5. will consider, any suggestion?

**Comment by mohsenkhanpour** [comment]
@ije 
1. Yes, I checked plugins and examples. What I meant was like a more elaborate API, for example Gatsbyjs provides some hooks to Gatsby lifecycle like `onPreBuild`,`onPostBuild` ... 
also as I see now plugins don't accept options.
For example config for plugin could be:
```
// For default options:
plugins: [`aleph-plugin-sass`] 
// For customized option:
plugins: [
  {
    resolve: `aleph-plugin-sass`,
    options: {
      postCssPlugins: [somePostCssPlugin()],
      precision: 6,
    },
  },
]
```
also having a naming convention for plugins would be very helpful, Gatsby uses like : 
`gatsby-plugin-*` : For general plugins like sass, less, analytics, CSP, manifest.
`gatsby-transformer-*` : For transformers plugins like image optimization, markdown transformation.
`gatsby-source-*` : For sourcing data during build. Using these plugins you can source data from many source: markdown, yaml, wordpress, ....
`gatsby-theme-*`: These are themes that come with preconfigured options.

Having these kinds of convention can give meaningful purpose to plugin system and lead to a rich ecosystem.

2. Yes. What I meant was like less tangled folder structure. This is not necessary now as you said, however as the number of examples and plugins increase it could be a wise idea.

3. I wasn't talking about this repository, I was talking about the application. In the docs it says put your static files in `public` folder, and build command outputs a `output` folder. 
Using `public` folder to hold static assets may cause hosting automation to think it should serve `public` folder, whereas it should serve `output` folder.
Using `static` folder for static assets, and building to `public` is more conventional.

5. Just [create](https://support.discord.com/hc/en-us/articles/204849977-How-do-I-create-a-server-) a server, and put the link on the website/repo Readme.md , and please invite us.

**Comment by mohsenkhanpour** [comment]
@ije 
Also supporting CSS modules:
```js
// For global CSS
import ".\style.css"
```
and 
```
// For CSS modules
import styles from ".\style.module.css"
```

**Comment by ije** [comment]
@mohsenkhanpour 
1. the plugin system is vary simple, currently only support **module import resolve** and **transform code**, since we don't use webpack/rollup/babel.
3. oh sorry! i think `static` should be a sub-folder of the `public` folder, Aleph.js server will serve the `public` dir as root directly. All files in `public` folder will be copied to `output` dir by **SSG**
**for example**, you want put some javascript or css, even wasm files in your application `public` and you have some images:
    - /public/static/images/logo.png -> /static/images/logo.png
    - /public/styles/global.css -> /styles/global.css 
    - /public/scritps/42.wasm -> /scritps/42.wasm
    - /public/ga.js -> /ga.js
    - /public/favicon.icon -> /favicon.icon

**Comment by ije** [comment]
@mohsenkhanpour **CSS modules** will be supported directly in the future.

**Comment by shinspiegel** [comment]
What is needed for the API functions to be available in the Vercel?

**Comment by shadowtime2000** [comment]
@shinspiegel If you take [a look at the serverless functions Vercel docs](https://vercel.com/docs/serverless-functions/introduction) it seems like only NodeJS is supported for serverless functions. Once Deno is supported, it should be able to work fine, though it may need some communication with the team on serverless functions for Vercel.

**Comment by shadowtime2000** [comment]
@ije For full testing do you think we could use Deno's unstable test coverage feature with a CI for test coverage?

**Comment by ije** [comment]
@shinspiegel @shadowtime2000 this https://github.com/TooTallNate/vercel-deno can help, we should fork it to support aleph's routing

**Comment by mohsenkhanpour** [comment]
I have tried serverless with Deno, Vercel definitely supports it. Vercel also support Python, Ruby and Go.
Netlify Functions currently support JavaScript (with the option to bundle npm dependencies from package.json) and Go.
@ije @shadowtime2000 @shinspiegel 
As far as I know serverless functions are not dependent on the client side library. You send a request and you receive a response.
Routing is often handled by client side routing libraries. I would say tying routing to serverless functions, and making it a requirement to use Vercel Deno for routing is an extremely fragile architecture.
Why do you say it should be forked to support Aleph's routing?

**Comment by ije** [comment]
@masataka The `APIRequest` of Aleph is not a standard `ServerRequest` of **std** which vercel-deno is using, we need to inject router info base on api file path and support dynamic api routes:

```typescript
// /api/hello/[name].ts

import type { APIRequest } from "https://deno.land/x/aleph/types.ts"

export default function handler(req: APIRequest) {
  req.status(200).json({ name: 'Hello ' + req.params.name })
}
```

This can not work in Vercel with **vercel-deno**.

**Comment by mohsenkhanpour** [comment]
@ije I see. I confused it with client side routes, however you are refereeing to API routes.
It's like server routes of Sapper, and Dynamic api routes of Next.js.
So these API dynamic routes will also work for dev server, and production server (for example if you want to self host, Aleph).

**Comment by mohsenkhanpour** [comment]
> @shinspiegel @shadowtime2000 this https://github.com/TooTallNate/vercel-deno can help, we should fork it to support aleph's routing

Forking it would be a great idea. I suppose people who use other frameworks could also benefit from using Deno on the serverless side.

@ije  BTW have you thought of how to implement custom server (oak)? I see it is in the check list, but there isn't much discussion about it.

How does Sapper's custom server and custom API routing work?

This is the custom server of default Sapper template:
https://github.com/sveltejs/sapper-template/blob/master/src/server.js

To make it work with Vercel's dynamic routing they just `default` export the custom server instance.
https://github.com/thgh/vercel-sapper

It's a bit confusing. Is Vercel able to run custom server instance?

**Comment by shadowtime2000** [comment]
@mohsenkhanpour 

> It's a bit confusing. Is Vercel able to run custom server instance?

I don't believe so, Vercel runs on AWS Lambda and is purely serverless hence the cheaper pricings with frameworks like NextJS and BlitzJS (and soon AlephJS) with stuff like API routes

**Comment by mohsenkhanpour** [comment]
@shadowtime2000 It might be that https://github.com/thgh/vercel-sapper converts the custom server to serverless friendly code.

How do you think Aleph can implement custom server (eg. oak) in a serverless compatible way?

**Comment by shadowtime2000** [comment]
@mohsenkhanpour That is probably what is going on, NextJS says you can't get the advantages of a serverless architecture when using a custom server implementation, I think it is best to go with that for now... we can probably implement conversion or something in v0.4.

**Comment by shadowtime2000** [comment]
We could look into using an adapter system kind of like SvelteKit where you plug an adapter into the `aleph.config.(ts|js)`. It could be possible to have Vercel support with the [File System API](https://vercel.com/docs/more/adding-your-framework#file-system-api) though that sadly only supports Node. We could also just do it without the file system API. This requires some further research

**Comment by shadowtime2000** [comment]
It seems like with the new project restructure the only thing we need JSDoc in now is `redirect`. I guess JSDoc for internal code would be pretty cool because it makes it easier for potential contributors to understand the codebase.

**Comment by ije** [comment]
@shadowtime2000 good to hear that! writing JSDoc is always hard for me...

**Comment by ije** [comment]
@mohsenkhanpour @shadowtime2000 **Custom server** is ready in the latest brench.

with deno **std** http server: 

```ts
import { serve } from "https://deno.land/std/http/server.ts"
import { Application, Server } from "https://deno.land/x/aleph/server/mod.ts"

const app = new Appliaction() 
const server = new Server(app)
const s = serve({ port: 8080 })

for await (const r of s) {
  server.handle(r)
}
```

with **oak**: 

```ts
import { Application as Oak } from "https://deno.land/x/oak/mod.ts";
import { Application, Server } from "https://deno.land/x/aleph/server/mod.ts"

const oak = new Oak()
const app = new Appliaction() 
const server = new Server(app)

oak.use((ctx) => {
  server.handle(ctx.request)
})

await oak.listen({ port: 8080 })
```

**Comment by mohsenkhanpour** [comment]
Great work.  
I will update the website and write docs for it.
What is the default path for custom server?

**Comment by thegaryroberts** [comment]
Server choice of std vs oak might be an option that could be picked from when the Init UI (https://github.com/alephjs/aleph.js/pull/47) is in place. Could skip the need for documentation.

**Comment by shadowtime2000** [comment]
> Server choice of std vs oak might be an option that could be picked from when the Init UI (#47) is in place. Could skip the need for documentation.

I don't think this is the best way to do this - a custom server is a more "advanced" configuration so users should be able to implement it on their own.

**Comment by forgo** [comment]
```
  {/* import css */}
  <link rel="stylesheet" href="../styles/app.css" />
```

Will this be expanded to allow for `.scss` and `.sass` extensions when using the sass plugin?

I currently use the [`Import` component](https://alephjs.org/docs/basic-features/built-in-css-support#the-import-component)  to avoid the "Could not find module" error with the TS import of a `.scss`.

It seems awkward switching conventions using both CSS and SCSS if these smart transforms are going to be the direction moving forward.

**Comment by shadowtime2000** [comment]
I think that's a good idea. I believe @ije is rewriting the loader system right now so they could probably have the loader system hook into the smart JSX transforms.

**Comment by Hunam6** [comment]
I disagree, oak is the Deno module (not NodeJS too, only Deno) with the most stars listed on deno.land. It means that many people use it, this choice should be available.

**Comment by shadowtime2000** [comment]
@Hunam6 I don't think popularity should be the deciding factor. Just because many people use it shouldn't really mean that the choice should be available. Going for a custom server architecture instead of a basic serverless like option is something that should only done once you have a full grasp because if you mess up the entire app goes down. I think it is a good idea to instead kind of "force" people to read the docs on it so they can understand.

**Comment by hazae41** [comment]
What's the current state of Vercel API functions? I can help

I'm also watching this https://github.com/TooTallNate/vercel-deno
Maybe we could use it?

**Comment by Lite5h4dow** [comment]
this probably isnt the best place to put this but could anyone give me some pointers on making a plugin for Aleph?

**Comment by ije** [comment]
@Lite5h4dow the docs updating will land later includes the plugin writing guid!

**Comment by Lite5h4dow** [comment]
Thankyou 😊

**Comment by Lite5h4dow** [comment]
also with regards to the request body, is there going to be a way to get the json data from the body or are we stuck parsing a unit8array?

**Comment by ije** [comment]
@Lite5h4dow https://alephjs.org/docs/api-reference/plugin-api it is

**Comment by ije** [comment]
> What's the current state of Vercel API functions? I can help
> 
> Maybe we can fork vercel-deno? https://github.com/TooTallNate/vercel-deno

i implemented this forked from @lucacasonato prior works at https://github.com/alephjs/vercel-aleph

**Comment by josh-hemphill** [comment]
Is Vue/pluggable-frameworks still a v0.4.0 goal? There's no specific issue for it that I can find, so there's nothing listed under milestones about it either, just passing mentions.
